version: 2
workflows:
  version: 2
  test:
    jobs:
      - test-1.1
      - test-2.0
jobs:
  test-1.1:
    docker:
      - image: microsoft/dotnet:1.1-sdk
    steps:
      - run:
          name: install packages
          command: apt-get -q update && apt-get install -qy awscli
      - checkout
      - run: aws s3 cp s3://launchdarkly-pastebin/ci/dotnet/LaunchDarkly.Common.snk LaunchDarkly.Common.snk
      - run: dotnet restore
      - run: dotnet build src/LaunchDarkly.Common -f netstandard1.4
      - run: dotnet build src/LaunchDarkly.Common -f netstandard1.6
      - run: dotnet test test/LaunchDarkly.Common.Tests/LaunchDarkly.Common.Tests.csproj -f netcoreapp1.1
  test-2.0:
    docker:
      - image: microsoft/dotnet:2.0-sdk-jessie
    steps:
      - run:
          name: install packages
          command: apt-get -q update && apt-get install -qy awscli
      - checkout
      - run: aws s3 cp s3://launchdarkly-pastebin/ci/dotnet/LaunchDarkly.Common.snk LaunchDarkly.Common.snk
      - run: dotnet restore
      - run: dotnet build src/LaunchDarkly.Common -f netstandard2.0
      - run: dotnet test test/LaunchDarkly.Common.Tests/LaunchDarkly.Common.Tests.csproj -f netcoreapp2.0
