version: 2.1

workflows:
  version: 2
  test:
    jobs:
      - build-netstandard-2
      - test-netcore:
          name: .NET Standard 2.0 + .NET Core 3.1
          docker-image: mcr.microsoft.com/dotnet/core/sdk:3.1-focal
          build-target-framework: netstandard2.0
          test-target-framework: netcoreapp3.1
          requires:
            - build-netstandard-2
      - test-netcore:
          name: .NET Standard 2.0 + .NET 6.0
          docker-image: mcr.microsoft.com/dotnet/sdk:6.0-focal
          build-target-framework: netstandard2.0
          test-target-framework: net6.0
          requires:
            - build-netstandard-2
      - test-windows-netframework-4-6-2:
          name: .NET Framework 4.6.2

orbs:
  win: circleci/windows@1.0.0

jobs:
  build-netstandard-2:
    parameters:
      build-target-framework:
        type: string
        default: netstandard2.0
    docker:
      - image: mcr.microsoft.com/dotnet/core/sdk:3.1-focal
    environment:
      ASPNETCORE_SUPPRESSSTATUSMESSAGES: true
    steps:
      - checkout
      - restore_cache:
          keys: 
            - deps-<<parameters.build-target-framework>>-{{ checksum "src/LaunchDarkly.CommonSdk/LaunchDarkly.CommonSdk.csproj" }}
            # For these two-step builds, we're caching the NuGet dependencies twice:
            # 1. Here, where we're only building CommonSdk itself and not the test project, we cache
            # the packages with a key like "deps-netstandard2.0-xxxx" where "xxxx" only changes if the
            # CommonSdk project file changes.
            # 2. In the test-netcore job, we are loading dependencies for the test project which might
            # vary depending on which framework we're building the test project with. So we cache the
            # dependencies there with a key like "deps-netstandard2.0-netcoreapp2.1-xxxx-yyyy" where
            # the "yyyy" part will change if the project file for the test project changes.
      - run:
          name: restore LaunchDarkly.CommonSdk
          command: dotnet restore src/LaunchDarkly.CommonSdk
      - save_cache:
          key: deps-<<parameters.build-target-framework>>-{{ checksum "src/LaunchDarkly.CommonSdk/LaunchDarkly.CommonSdk.csproj" }}
          paths:
            - /root/.nuget/packages
      - run:
          name: build LaunchDarkly.CommonSdk
          command: dotnet build src/LaunchDarkly.CommonSdk -f <<parameters.build-target-framework>>
      - persist_to_workspace:
          root: src/LaunchDarkly.CommonSdk
          paths:
            - bin
            - obj

  test-netcore:
    parameters:
      docker-image:
        type: string
      build-target-framework:
        type: string
      test-target-framework:
        type: string
    docker:
      - image: <<parameters.docker-image>>
    environment:
      ASPNETCORE_SUPPRESSSTATUSMESSAGES: true
      TESTFRAMEWORK: <<parameters.test-target-framework>>
    steps:
      - checkout
      - attach_workspace:
          at: src/LaunchDarkly.CommonSdk
      - restore_cache:
          keys: # see comments under build-netstandard-2
            - deps-<<parameters.build-target-framework>>-<<parameters.test-target-framework>>-{{ checksum "src/LaunchDarkly.CommonSdk/LaunchDarkly.CommonSdk.csproj" }}-{{ checksum "test/LaunchDarkly.CommonSdk.Tests/LaunchDarkly.CommonSdk.Tests.csproj" }}
      - run:
          name: restore LaunchDarkly.CommonSdk.Tests
          command: dotnet restore test/LaunchDarkly.CommonSdk.Tests
      - save_cache:
          key: deps-<<parameters.build-target-framework>>-<<parameters.test-target-framework>>-{{ checksum "src/LaunchDarkly.CommonSdk/LaunchDarkly.CommonSdk.csproj" }}-{{ checksum "test/LaunchDarkly.CommonSdk.Tests/LaunchDarkly.CommonSdk.Tests.csproj" }}
          paths:
            - /root/.nuget/packages
      - run:
          name: run tests
          command: dotnet test test/LaunchDarkly.CommonSdk.Tests/LaunchDarkly.CommonSdk.Tests.csproj -f <<parameters.test-target-framework>>

  test-windows-netframework-4-6-2:
    executor:
      name: win/vs2019
      shell: powershell.exe
    environment:
      TESTFRAMEWORK: net462
    steps:
      - checkout
      - restore_cache:
          keys: # see comments under build-netstandard-2
            - deps-net462-net46-{{ checksum "src/LaunchDarkly.CommonSdk/LaunchDarkly.CommonSdk.csproj" }}-{{ checksum "test/LaunchDarkly.CommonSdk.Tests/LaunchDarkly.CommonSdk.Tests.csproj" }}
      - run:
          name: install project dependencies
          command: dotnet restore
      - save_cache:
          key: deps-net462-net46-{{ checksum "src/LaunchDarkly.CommonSdk/LaunchDarkly.CommonSdk.csproj" }}-{{ checksum "test/LaunchDarkly.CommonSdk.Tests/LaunchDarkly.CommonSdk.Tests.csproj" }}
          paths:
            - C:\Users\circleci\.nuget\packages
      - run:
          name: build SDK for .NET Framework 4.6.2
          command: dotnet build src/LaunchDarkly.CommonSdk -f net462
      - run:
          name: run tests in .NET Framework 4.6.2
          command: dotnet test test/LaunchDarkly.CommonSdk.Tests/LaunchDarkly.CommonSdk.Tests.csproj -f net462
