version: 2

repo:
  public: dotnet-sdk-common
  private: dotnet-sdk-common-private

branches:
  - name: master
    description: 6.x - for dotnet-client-sdk 3.0 & dotnet-server-sdk 7.0
  - name: 5.x
    description: for dotnet-client-sdk 2.0 & dotnet-server-sdk 6.0
  - name: 4.x
    description: for dotnet-client-sdk 1.0
  - name: 2.x
    description: for dotnet-server-sdk 5.0

publications:
  - url: https://nuget.org/packages/LaunchDarkly.CommonSdk
    description: NuGet

jobs:
  - docker: {}
    template:
      name: dotnet-linux
    env:
      LD_RELEASE_TEST_TARGET_FRAMEWORK: net50
      LD_RELEASE_DOCS_TARGET_FRAMEWORK: netstandard2.0

# Note that we don't publish HTML docs for this project, because it will be included
# in the API docs for the actual SDKs. However, we do still do a docs build during
# the release, so we can verify that the XML comments are well-formed, and also so
# can preview the docs in a dry run.
documentation:
  title: .NET SDK Common Types
