name: Build and Test

on:
  push:
    branches: [main, feat/**]
    paths-ignore:
      - '**.md' #Do not need to run CI for markdown changes.
  pull_request:
    branches: [main, feat/**]
    paths-ignore:
      - '**.md'

jobs:
  build-test-netcore:
    strategy:
      matrix:
        framework:
          - { build_target: 'netstandard2.0', test_target: 'netcoreapp3.1', image: 'sdk:3.1-focal' }
          - { build_target: 'netstandard2.0', test_target: 'net6.0', image: 'sdk:6.0-focal' }
    runs-on: ubuntu-latest
    container: mcr.microsoft.com/dotnet/${{ matrix.framework.image }}
    env:
      ASPNETCORE_SUPPRESSSTATUSMESSAGES: true
      BUILDFRAMEWORKS: ${{ matrix.framework.build_target }}
      TESTFRAMEWORK: ${{ matrix.framework.test_target }}
    steps:
      - uses: actions/checkout@v3

      - name: Shared CI Steps
        uses: ./.github/actions/ci
        with:
          framework_build_target: ${{ matrix.framework.build_target }}
          framework_test_target: ${{ matrix.framework.test_target }}

  build-test-netframework:
    strategy:
      matrix:
        framework_target: [net462]
    runs-on: windows-latest
    env:
      ASPNETCORE_SUPPRESSSTATUSMESSAGES: true
      BUILDFRAMEWORKS: ${{ matrix.framework_target }}
      TESTFRAMEWORK: ${{ matrix.framework_target }}
    steps:
      - uses: actions/checkout@v3

      - name: Shared CI Steps
        uses: ./.github/actions/ci
        with:
          framework_build_target: ${{ matrix.framework_target }}
          framework_test_target: ${{ matrix.framework_target }}
